Output gollama.gif
Set Theme "catppuccin-mocha"
Set WindowBar Colorful
Set FontSize 18
Set Width 1200
Set Height 800
Set Margin 20
Set MarginFill "#674EFF"
Set BorderRadius 10
Set Shell zsh
Type "gollama"
Enter
Sleep 3s
Ctrl+N
Sleep 1s
Type "new chat"
Enter 2
Sleep 500ms
Enter
Sleep 1.5s
Enter
Type "hello world"
Enter
Sleep 4s
Type "reverse a string in go"
Enter
Sleep 7.5s
Ctrl+P
Ctrl+P
Ctrl+P
Sleep 500ms
Ctrl+C
Sleep 500ms
Enter
Sleep 2s
Ctrl+D
